# Generated by Django 6.0.1 on 2026-01-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_discounttypes_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountTypes',
        ),
        migrations.RemoveField(
            model_name='historicaldiscounttypes',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmovementtypes',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpaymenttypes',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='MovementTypes',
        ),
        migrations.DeleteModel(
            name='PaymentTypes',
        ),
        migrations.DeleteModel(
            name='HistoricalDiscountTypes',
        ),
        migrations.DeleteModel(
            name='HistoricalMovementTypes',
        ),
        migrations.DeleteModel(
            name='HistoricalPaymentTypes',
        ),
    ]
