# Generated by Django 5.2.1 on 2025-10-04 21:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFingerprints',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated/Deactivated')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('finger', models.CharField(choices=[('left_thumb', 'Pulgar izquierdo'), ('left_index', 'Índice izquierdo'), ('left_middle', 'Medio izquierdo'), ('left_ring', 'Anular izquierdo'), ('left_little', 'Meñique izquierdo'), ('right_thumb', 'Pulgar derecho'), ('right_index', 'Índice derecho'), ('right_middle', 'Medio derecho'), ('right_ring', 'Anular derecho'), ('right_little', 'Meñique derecho')], max_length=20, verbose_name='Dedo registrado')),
                ('template', models.BinaryField(help_text='Datos binarios del patrón extraído del lector', verbose_name='Plantilla biométrica')),
                ('device_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Fingerprint',
                'verbose_name_plural': 'historical Fingerprints',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Fingerprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated/Deactivated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Deleted At')),
                ('finger', models.CharField(choices=[('left_thumb', 'Pulgar izquierdo'), ('left_index', 'Índice izquierdo'), ('left_middle', 'Medio izquierdo'), ('left_ring', 'Anular izquierdo'), ('left_little', 'Meñique izquierdo'), ('right_thumb', 'Pulgar derecho'), ('right_index', 'Índice derecho'), ('right_middle', 'Medio derecho'), ('right_ring', 'Anular derecho'), ('right_little', 'Meñique derecho')], max_length=20, verbose_name='Dedo registrado')),
                ('template', models.BinaryField(help_text='Datos binarios del patrón extraído del lector', verbose_name='Plantilla biométrica')),
                ('device_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fingerprint',
                'verbose_name_plural': 'Fingerprints',
                'unique_together': {('user', 'finger')},
            },
        ),
    ]
