# Generated by Django 5.2.1 on 2025-10-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_historicalfingerprints_fingerprints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusers',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='historicalusers',
            name='password',
        ),
        migrations.AlterField(
            model_name='fingerprints',
            name='finger',
            field=models.CharField(choices=[('left_thumb', 'Pulgar izquierdo'), ('left_index', 'Índice izquierdo'), ('left_middle', 'Medio izquierdo'), ('left_ring', 'Anular izquierdo'), ('left_little', 'Meñique izquierdo'), ('right_thumb', 'Pulgar derecho'), ('right_index', 'Índice derecho'), ('right_middle', 'Medio derecho'), ('right_ring', 'Anular derecho'), ('right_little', 'Meñique derecho')], max_length=20, verbose_name='Finger'),
        ),
        migrations.AlterField(
            model_name='historicalfingerprints',
            name='finger',
            field=models.CharField(choices=[('left_thumb', 'Pulgar izquierdo'), ('left_index', 'Índice izquierdo'), ('left_middle', 'Medio izquierdo'), ('left_ring', 'Anular izquierdo'), ('left_little', 'Meñique izquierdo'), ('right_thumb', 'Pulgar derecho'), ('right_index', 'Índice derecho'), ('right_middle', 'Medio derecho'), ('right_ring', 'Anular derecho'), ('right_little', 'Meñique derecho')], max_length=20, verbose_name='Finger'),
        ),
    ]
