# Generated by Django 5.2.1 on 2025-10-09 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_discounttypes_options_and_more'),
        ('shared', '0001_initial'),
        ('user', '0005_alter_accesslogs_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusers',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='users',
            name='rol',
        ),
        migrations.AddField(
            model_name='historicalusers',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shared.cities', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='historicalusers',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shared.countries', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='historicalusers',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.roles', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='shared.cities', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='shared.countries', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.roles', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='accesslogs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='fingerprints',
            name='device_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Serial Number'),
        ),
        migrations.AlterField(
            model_name='fingerprints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalaccesslogs',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalfingerprints',
            name='device_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Serial Number'),
        ),
        migrations.AlterField(
            model_name='historicalfingerprints',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalroles',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='historicalroles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalroles',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='document_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.documenttypes', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='username',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.documenttypes', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/image/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
