# Generated by Django 5.2.1 on 2025-10-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategories',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='historicalexpensecategories',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='historicalexpenses',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='historicalmermas',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='historicalsuppliers',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='historicalvouchers',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='mermas',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
    ]
