# Generated by Django 5.2.1 on 2025-10-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expensecategories_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalmermas',
            old_name='lost_modey',
            new_name='lost_money',
        ),
        migrations.RenameField(
            model_name='mermas',
            old_name='lost_modey',
            new_name='lost_money',
        ),
    ]
