# Generated by Django 5.2.1 on 2025-09-23 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('expense', '0004_alter_historicalmermas_lost_modey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalexpenses',
            name='payment_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.paymenttypes'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paymenttypes'),
        ),
        migrations.DeleteModel(
            name='HistoricalPaymentTypes',
        ),
        migrations.DeleteModel(
            name='PaymentTypes',
        ),
    ]
