# Generated by Django 5.2.1 on 2025-10-08 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_discounttypes_options_and_more'),
        ('expense', '0004_rename_lost_modey_historicalmermas_lost_money_and_more'),
        ('product', '0002_alter_historicalproductcategories_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='mermas',
            options={'ordering': ['-date'], 'verbose_name': 'Merma', 'verbose_name_plural': 'Mermas'},
        ),
        migrations.AlterField(
            model_name='expensecategories',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.expensecategories'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymenttypes'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='product.products'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expense.suppliers'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expense.vouchers'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='voucher_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Comprobante'),
        ),
        migrations.AlterField(
            model_name='historicalexpensecategories',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalexpenses',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalexpenses',
            name='voucher_number',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Número de Comprobante'),
        ),
        migrations.AlterField(
            model_name='historicalmermas',
            name='lost_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Dinero perdido'),
        ),
        migrations.AlterField(
            model_name='historicalsuppliers',
            name='ruc',
            field=models.CharField(db_index=True, max_length=11, verbose_name='Ruc'),
        ),
        migrations.AlterField(
            model_name='historicalvouchers',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Payment Voucher Name'),
        ),
        migrations.AlterField(
            model_name='mermas',
            name='lost_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Dinero perdido'),
        ),
        migrations.AlterField(
            model_name='mermas',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.products'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='ruc',
            field=models.CharField(max_length=11, unique=True, verbose_name='Ruc'),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Payment Voucher Name'),
        ),
    ]
