# Generated by Django 5.2.1 on 2025-09-25 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_alter_historicalexpenses_payment_type_and_more'),
        ('product', '0007_historicalproducts_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='product.products'),
        ),
    ]
