# Generated by Django 5.2.1 on 2025-10-04 23:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_historicalusers_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated/Deactivated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Deleted At')),
                ('device_serial_number', models.CharField(help_text='Número de serie o identificador del lector que registró el acceso.', max_length=100, verbose_name='Dispositivo lector')),
                ('verified', models.BooleanField(default=False, verbose_name='Huella verificada')),
                ('access_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida')], default='entry', max_length=10, verbose_name='Tipo de acceso')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del acceso')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas o detalles')),
                ('fingerprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='user.fingerprints', verbose_name='Huella usada')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'AccessLog',
                'verbose_name_plural': 'AccessLogs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccessLogs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated/Deactivated')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('device_serial_number', models.CharField(help_text='Número de serie o identificador del lector que registró el acceso.', max_length=100, verbose_name='Dispositivo lector')),
                ('verified', models.BooleanField(default=False, verbose_name='Huella verificada')),
                ('access_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida')], default='entry', max_length=10, verbose_name='Tipo de acceso')),
                ('timestamp', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha y hora del acceso')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas o detalles')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fingerprint', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.fingerprints', verbose_name='Huella usada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'historical AccessLog',
                'verbose_name_plural': 'historical AccessLogs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
