# Generated by Django 5.2.1 on 2025-10-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitems_deleted_at_alter_carts_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carts',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalcartitems',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
