# Generated by Django 5.2.1 on 2025-10-09 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_discounttypes_options_and_more'),
        ('product', '0004_alter_productcomponents_subproduct_and_more'),
        ('sale', '0002_alter_customers_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-id'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.RemoveField(
            model_name='historicalsaledetails',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='historicalsales',
            name='total',
        ),
        migrations.RemoveField(
            model_name='saledetails',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total',
        ),
        migrations.AddField(
            model_name='historicalsaledetails',
            name='subtotal_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='historicalsales',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saledetails',
            name='subtotal_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.documenttypes', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='internal',
            field=models.BooleanField(default=False, help_text='Indica si el cliente es un usuario interno del sistema', verbose_name='Internal'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='document_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.documenttypes', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='internal',
            field=models.BooleanField(default=False, help_text='Indica si el cliente es un usuario interno del sistema', verbose_name='Internal'),
        ),
        migrations.AlterField(
            model_name='historicalcustomers',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='historicalsaledetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicalsaledetails',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='historicalsaledetails',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='historicalsaledetails',
            name='sale',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.sales', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='historicalsales',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.customers', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='historicalsales',
            name='date',
            field=models.DateField(blank=True, editable=False, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='historicalsales',
            name='payment_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.paymenttypes', verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='historicalsales',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='product.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='sale.sales', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sale.customers', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymenttypes', verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
