# Generated by Django 5.2.1 on 2025-10-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_sales_options_and_more'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='shared.cities', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customers',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='shared.countries', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='historicalcustomers',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shared.cities', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='historicalcustomers',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shared.countries', verbose_name='Country'),
        ),
    ]
