# Generated by Django 5.2.1 on 2025-10-10 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('product', '0004_alter_productcomponents_subproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventorymovements',
            name='balance',
            field=models.IntegerField(default=0, editable=False, help_text='Saldo resultante después del movimiento', verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='inventorymovements',
            name='balance',
            field=models.IntegerField(default=0, editable=False, help_text='Saldo resultante después del movimiento', verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='inventorymovements',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='inventory.warehouses', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.warehouses', verbose_name='Warehouse'),
        ),
    ]
