# Generated by Django 5.2.1 on 2025-10-02 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('expense', '0003_initial'),
        ('inventory', '0001_initial'),
        ('product', '0001_initial'),
        ('sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventorymovements',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinventorymovements',
            name='movement_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.movementtypes'),
        ),
        migrations.AddField(
            model_name='historicalinventorymovements',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.products'),
        ),
        migrations.AddField(
            model_name='historicalinventorymovements',
            name='reference_expense',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='expense.expenses'),
        ),
        migrations.AddField(
            model_name='historicalinventorymovements',
            name='reference_sale',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.sales'),
        ),
        migrations.AddField(
            model_name='historicalstocks',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstocks',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.products'),
        ),
        migrations.AddField(
            model_name='inventorymovements',
            name='movement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='core.movementtypes'),
        ),
        migrations.AddField(
            model_name='inventorymovements',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='product.products'),
        ),
        migrations.AddField(
            model_name='inventorymovements',
            name='reference_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='expense.expenses'),
        ),
        migrations.AddField(
            model_name='inventorymovements',
            name='reference_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='sale.sales'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.products'),
        ),
    ]
