# Generated by Django 5.2.1 on 2025-10-10 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_historicalinventorymovements_balance_and_more'),
        ('product', '0004_alter_productcomponents_subproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='product.products', verbose_name='Product'),
        ),
    ]
