# Generated by Django 5.2.1 on 2025-10-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_historicalinventorymovements_deleted_at_and_more'),
        ('product', '0002_alter_historicalproductcategories_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovements',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory Movement', 'verbose_name_plural': 'Inventory Movements'},
        ),
        migrations.RenameField(
            model_name='historicalinventorymovements',
            old_name='reference_expense',
            new_name='expense',
        ),
        migrations.RenameField(
            model_name='historicalinventorymovements',
            old_name='reference_sale',
            new_name='sale',
        ),
        migrations.RenameField(
            model_name='inventorymovements',
            old_name='reference_expense',
            new_name='expense',
        ),
        migrations.RenameField(
            model_name='inventorymovements',
            old_name='reference_sale',
            new_name='sale',
        ),
        migrations.AlterField(
            model_name='historicalinventorymovements',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas o comentarios del movimiento.', null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovements',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas o comentarios del movimiento.', null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.products'),
        ),
    ]
