# Generated by Django 5.2.1 on 2025-10-08 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorymovements_options_and_more'),
        ('product', '0002_alter_historicalproductcategories_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovements',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='product.products'),
        ),
    ]
