# Generated by Django 5.2.1 on 2025-10-09 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_discounttypes_options_and_more'),
        ('expense', '0005_alter_expenses_options_alter_mermas_options_and_more'),
        ('inventory', '0006_alter_inventorymovements_product'),
        ('product', '0004_alter_productcomponents_subproduct_and_more'),
        ('sale', '0004_customers_city_customers_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventorymovements',
            name='balance',
            field=models.IntegerField(default=0, help_text='Saldo resultante después del movimiento', verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='historicalinventorymovements',
            name='expense',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='expense.expenses', verbose_name='Expense'),
        ),
        migrations.AlterField(
            model_name='historicalinventorymovements',
            name='movement_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.movementtypes', verbose_name='Movement Type'),
        ),
        migrations.AlterField(
            model_name='historicalinventorymovements',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas o comentarios del movimiento.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='historicalinventorymovements',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='historicalinventorymovements',
            name='quantity',
            field=models.IntegerField(help_text='Cantidad del movimiento, puede ser positiva (IN) o negativa (OUT)', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='historicalinventorymovements',
            name='sale',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.sales', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='historicalstocks',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='historicalstocks',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Cantidad actual en stock físico', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='inventorymovements',
            name='balance',
            field=models.IntegerField(default=0, help_text='Saldo resultante después del movimiento', verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='inventorymovements',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='expense.expenses', verbose_name='Expense'),
        ),
        migrations.AlterField(
            model_name='inventorymovements',
            name='movement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='core.movementtypes', verbose_name='Movement Type'),
        ),
        migrations.AlterField(
            model_name='inventorymovements',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas o comentarios del movimiento.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='inventorymovements',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='product.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='inventorymovements',
            name='quantity',
            field=models.IntegerField(help_text='Cantidad del movimiento, puede ser positiva (IN) o negativa (OUT)', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='inventorymovements',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='sale.sales', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Cantidad actual en stock físico', verbose_name='Quantity'),
        ),
    ]
