# Generated by Django 5.2.1 on 2025-10-02 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcategoriesproduct',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproducts',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.categoriesproduct', verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='historicalproducts',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproducts',
            name='measure_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.measureunits', verbose_name='Measure Unit'),
        ),
        migrations.AddField(
            model_name='historicalpromotions',
            name='discount_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.discounttypes', verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='historicalpromotions',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoriesproduct', verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='products',
            name='measure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.measureunits', verbose_name='Measure Unit'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='product.categoriesproduct'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='core.discounttypes', verbose_name='Discount Type'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='product.products'),
        ),
    ]
