# Generated by Django 5.2.1 on 2025-10-08 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_historicalproductcategories_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductcategories',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalproducts',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='historicalproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio final de venta al cliente.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio final de venta al cliente.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sale Price'),
        ),
    ]
