# Generated by Django 5.2.1 on 2025-10-02 23:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_historicalproductcomponents_productcomponents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalCategoriesProduct',
            new_name='HistoricalProductCategories',
        ),
        migrations.RenameModel(
            old_name='CategoriesProduct',
            new_name='ProductCategories',
        ),
        migrations.AlterModelOptions(
            name='historicalproductcategories',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Product Categorie', 'verbose_name_plural': 'historical Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productcategories',
            options={'verbose_name': 'Product Categorie', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
