# Generated by Django 5.2.1 on 2025-10-08 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_discounttypes_options_and_more'),
        ('product', '0003_alter_historicalproductcategories_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponents',
            name='subproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='product.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productcategories', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='measure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.measureunits', verbose_name='Measure Unit'),
        ),
    ]
