# Generated by Django 5.2.1 on 2025-09-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_historicalcategoriesproduct_historicalindicators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducts',
            name='descount_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='descount_value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
