# Generated by Django 5.2.1 on 2025-10-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productcomponents_subproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducts',
            name='is_digital',
            field=models.BooleanField(default=False, verbose_name='Is Digital'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_digital',
            field=models.BooleanField(default=False, verbose_name='Is Digital'),
        ),
    ]
