# Generated by Django 5.2.1 on 2025-09-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_historicalproducts_descount_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalindicators',
            old_name='descount_value',
            new_name='discount_value',
        ),
        migrations.RenameField(
            model_name='historicalproducts',
            old_name='descount_value',
            new_name='discount_value',
        ),
        migrations.RenameField(
            model_name='indicators',
            old_name='descount_value',
            new_name='discount_value',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='descount_value',
            new_name='discount_value',
        ),
    ]
