# Generated by Django 5.2.1 on 2025-09-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_descount_value_historicalindicators_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio final de venta al cliente.', max_digits=10, verbose_name='Sale Price'),
        ),
        migrations.AddField(
            model_name='historicalproducts',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje de ganancia sobre el costo.', max_digits=5, verbose_name='Profit (%)'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio final de venta al cliente.', max_digits=10, verbose_name='Sale Price'),
        ),
        migrations.AddField(
            model_name='products',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje de ganancia sobre el costo.', max_digits=5, verbose_name='Profit (%)'),
        ),
    ]
