# Generated by Django 5.2.1 on 2025-09-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_historicalpromotions_promotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators',
            name='category',
        ),
        migrations.DeleteModel(
            name='HistoricalIndicators',
        ),
        migrations.DeleteModel(
            name='Indicators',
        ),
    ]
