# Generated by Django 5.2.1 on 2025-09-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_indicators_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducts',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discount_value',
        ),
    ]
