# Generated by Django 5.2.1 on 2025-10-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_discounttypes_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounttypes',
            options={'ordering': ['code'], 'verbose_name': 'Discount Type', 'verbose_name_plural': 'Discount Types'},
        ),
        migrations.AlterModelOptions(
            name='documenttypes',
            options={'ordering': ['code'], 'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
        migrations.AlterModelOptions(
            name='measureunits',
            options={'ordering': ['code'], 'verbose_name': 'Measure Unit', 'verbose_name_plural': 'Measure Units'},
        ),
        migrations.AlterModelOptions(
            name='movementtypes',
            options={'ordering': ['code'], 'verbose_name': 'Movement Type', 'verbose_name_plural': 'Movement Types'},
        ),
        migrations.AlterModelOptions(
            name='paymenttypes',
            options={'ordering': ['code'], 'verbose_name': 'Payment Type', 'verbose_name_plural': 'Payment Types'},
        ),
        migrations.AlterField(
            model_name='discounttypes',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='discounttypes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='discounttypes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='documenttypes',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='documenttypes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='documenttypes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicaldiscounttypes',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='historicaldiscounttypes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaldiscounttypes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicaldocumenttypes',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='historicaldocumenttypes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaldocumenttypes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunits',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunits',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunits',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalmovementtypes',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='historicalmovementtypes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalmovementtypes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalpaymenttypes',
            name='code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='historicalpaymenttypes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalpaymenttypes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='measureunits',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='measureunits',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='measureunits',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='movementtypes',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='movementtypes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='movementtypes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='paymenttypes',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='paymenttypes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='paymenttypes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
